services:
  inference:
    container_name: inference
    build:
      context: .
    command: gunicorn --config /app/gunicorn_conf.py app:app
    ports:
      - "8011:8011"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8011/inference/ETH || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 600s  # Tăng thời gian chờ trước khi bắt đầu kiểm tra
    volumes:
      - ./inference-data:/app/data
    environment:
      - LOGGING_LEVEL=INFO
      - WORKERS=2  # Define number of workers for gunicorn
      - THREADS=4  # Define number of threads per worker

  updater:
    container_name: updater
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8011
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 600;
      done
      "
    depends_on:
      inference:
        condition: service_healthy
    volumes:
      - ./inference-data:/app/data

  worker:
    container_name: worker
    image: alloranetwork/allora-offchain-node:latest
    volumes:
      - ./worker-data:/data
    working_dir: /data
    depends_on:
      inference:
        condition: service_healthy
    env_file:
      - ./worker-data/env_file
    entrypoint: ["/node/allora_offchain_node"]

volumes:
  inference-data:
  worker-data:
